baseURL = "https://chaitanyav.github.io/"
languageCode = "en-us"
enableEmoji = true
title = "NagaChaitanya Vellanki's blog"
theme = "hugo_theme_pickles"
publishDir = "chaitanyav.github.io"
[params]
  avatar = "/avatar.png"
  github = "chaitanyav"
  contact = "mailto:pnagato@protonmail.com"
  linkedin = "nagachaitanya"
  flickr = "76625390@N03"
  custom_css = ["/css/custom.css"]
[markup]
  defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
      [markup.goldmark.renderer]
	unsafe = true

[[menu.main]]
  name = "Origami"
  url = "/origami"
  weight = 100
[[menu.main]]
  name = "Fractals"
  url = "/fractals"
  weight = 100
[[menu.main]]
  name = "Diversions"
  url = "/diversions"
  weight = 100
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 100
[[menu.main]]
  name = "Open Source"
  url = "/open_source"
  weight = 100
[[menu.main]]
  name = "Posts"
  url = "/posts"
[[menu.main]]
  name = "Books Read"
  url = "/books"
